- name: Install nginx
  ansible.builtin.yum:
    name: httpd
    state: installed
    
- name: Remove old HTTP Documents
  ansible.debuiltin.file:
     path: /usr/share/nginx/html
     state: absent     