- name: Configure NogeJS repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
    
- name: Install NodeJS
  ansible.builtin.yum:
    name: NodeJS
    state: Installed  

- name: Add Application User
  ansible.builtin.user:
    name: roboshop

 - name: Remove old content
  ansible.builtin.file:
     path: /app
     state: absent     

- name: Create a app directory      
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download frontend app content
  ansible.builtin.unarchive:
     src: http://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
     dest: /app
     remote_src: yes   

- name: Install NodeJS dependencies
  community.general.npm:
    path: /app
    state: latest     
    