- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Remove old content
  ansible.builtin.file:
    path: /app
    state: absent     

- name: Create a app directory      
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download {{component}} app content
  ansible.builtin.unarchive:
     src: http://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
     dest: /app
     remote_src: yes 