- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Add Application User
  ansible.builtin.user:
    name: roboshop

- name: Remove old content
  ansible.builtin.file:
    path: /app
    state: absent     

- name: Create a app directory      
  ansible.builtin.file:
    path: /app
    state: directory

# - name: Download {{component}} app content
#   ansible.builtin.unarchive:
#      src: http://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
#      dest: /app
#      remote_src: yes 

- name: Download {{component}} app content
  ansible.builtin.unarchive:
     src: http://{{nexus_user}}:{{nexus_pass}}@172.31.94.53:8081/repository//{{component}}/{{component}}-{{app_version}}.zip
     dest: /app
     remote_src: yes    
  vars:
   nexus_user: {{ lookup('aws_ssm', "nexus.user", region='us-east-1' ) }}
   nexus_pass: {{ lookup('aws_ssm', "nexus.pass", region='us-east-1' ) }}     